name: Main
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Build library
              run: npm run build
            - uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: |
                      dist
                      dist-es5
                      typings
    build-example:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v2
            - uses: actions/download-artifact@v2
              with:
                  name: build
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Build example
              run: npm run build-example
            - uses: actions/upload-artifact@v2
              with:
                  name: example
                  path: example
    deploy-example:
        runs-on: ubuntu-latest
        needs: build-example
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: example
                  path: example
            - uses: google-github-actions/auth@v0.4.0
              with:
                  credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
            - uses: google-github-actions/upload-cloud-storage@v0.4.0
              with:
                  path: example/index.html
                  destination: ${{ secrets.GCP_BUCKET }}/${{ github.sha }}.html
                  parent: false
